### ISSUE TITLE
Attribution?

### ISSUE THREAD

**Issue by raybellis** [tamb/object-bystring#15]
There's no attribution to the original source for the code.

**Comment by tamb** [comment]
Certainly! Just saw that I got the original code from your SO post! I will add this in asap
https://stackoverflow.com/questions/6491463/accessing-nested-javascript-objects-with-string-key

**Comment by tamb** [comment]
@raybellis I've added to the README.md. Is that good?  Also, sorry I didnt have your attribution before.
