### ISSUE TITLE
Return value not as advertised 

### ISSUE THREAD

**Issue by calvintennant** [tamb/object-bystring#31]
I tried the demo attached to your readme. This works as expected, where when I provide an accessor I get it's associated value. The project available on NPM however, does not work this way.

Consider the following object:
```
{
    person: {
        name: "Joe",
        age: 33,
    }
}
```

Expected result for accessor `person.name` is `Joe` as a string. Actual result was an object like `{ name: Joe }`.

**Comment by EskelCz** [comment]
Found the same thing, the polyfill returns the parent object instead of undefined.

**Comment by tamb** [comment]
I'll look into this today. Finally got time

**Comment by tamb** [comment]
@calvintennant Can you show me the code you're using that's surfacing the bug?

**Comment by tamb** [comment]
I'm going to deprecate previous versions. `5.0.3` onward should work.
